In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/organizations/uciml/iris/Iris.csv
/kaggle/input/datasets/organizations/uciml/iris/database.sqlite


# Chapter 4 — Reshaping and Managing Arrays

Welcome to Chapter 4 of NumPy.

In this chapter, we will learn how to reorganize and manage NumPy arrays efficiently.

After learning array operations and statistical functions, the next important step is understanding how arrays can be reshaped and combined for better data handling.

This chapter focuses on:
- Changing array dimensions
- Converting arrays into different structures
- Combining arrays
- Splitting arrays
- Handling missing values

These concepts are important because NumPy arrays are often transformed into different shapes for calculations and processing.

---

# Topics Covered

1. Reshaping Arrays  
2. Flattening Arrays  
3. Combining Arrays  
4. Splitting Arrays  
5. Handling Missing Values using `np.nan`

---

# 1. Reshaping Arrays

## Definition

Reshaping is the process of changing the dimensions of an array without changing its data.

---

## Working

Sometimes arrays are stored in one structure but needed in another structure.

Example:

```python
[1, 2, 3, 4, 5, 6]
```

can be reshaped into:

```python
[
 [1, 2, 3],
 [4, 5, 6]
]
```

The total number of elements must remain the same.

---

## Syntax

```python
array.reshape(rows, columns)
```

---

## Example

```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)

print(reshaped)
```

## Output

```python
[[1 2 3]
 [4 5 6]]
```

---

# 2. Flattening Arrays

## Definition

Flattening converts a multi-dimensional array into a one-dimensional array.

---

## Working

A 2D array:

```python
[
 [1, 2],
 [3, 4]
]
```

becomes:

```python
[1, 2, 3, 4]
```

Flattening helps simplify arrays into a single row of elements.

---

## Syntax

```python
array.flatten()
```

---

## Example

```python
import numpy as np

matrix = np.array([
    [1, 2],
    [3, 4]
])

print(matrix.flatten())
```

## Output

```python
[1 2 3 4]
```

---

# 3. Combining Arrays

## Definition

Combining arrays means joining multiple arrays together into a single array.

---

## Working

NumPy allows arrays to be joined:
- vertically
- horizontally

Example:

```python
[1, 2]
```

and

```python
[3, 4]
```

can become:

```python
[1, 2, 3, 4]
```

---

## Syntax

```python
np.concatenate((array1, array2))
```

---

## Example

```python
import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

combined = np.concatenate((arr1, arr2))

print(combined)
```

## Output

```python
[1 2 3 4]
```

---

# 4. Splitting Arrays

## Definition

Splitting arrays means dividing one array into multiple smaller arrays.

---

## Working

Example:

```python
[1, 2, 3, 4]
```

can be split into:

```python
[1, 2]
```

and

```python
[3, 4]
```

This helps organize data into smaller sections.

---

## Syntax

```python
np.split(array, sections)
```

---

## Example

```python
import numpy as np

arr = np.array([1, 2, 3, 4])

split_array = np.split(arr, 2)

print(split_array)
```

## Output

```python
[array([1, 2]), array([3, 4])]
```

---

# 5. Handling Missing Values using np.nan

## Definition

`np.nan` represents missing or undefined numerical values in NumPy.

---

## Working

Sometimes data may contain missing values.

NumPy uses:

```python
np.nan
```

to represent those missing values.

Example:

```python
[10, 20, nan, 40]
```

Here:
- third value is missing

---

## Example

```python
import numpy as np

arr = np.array([10, 20, np.nan, 40])

print(arr)
```

## Output

```python
[10. 20. nan 40.]
```

---

# Checking Missing Values

## Syntax

```python
np.isnan(array)
```

---

## Example

```python
import numpy as np

arr = np.array([10, 20, np.nan, 40])

print(np.isnan(arr))
```

## Output

```python
[False False  True False]
```

`True` indicates the missing value position.

---

# Chapter Summary

In this chapter, we learned:
- How to reshape arrays
- How to flatten arrays
- How to combine arrays
- How to split arrays
- How to handle missing values using `np.nan`

These concepts are important for organizing and managing NumPy arrays efficiently.

# Practice Question

Create a NumPy array:

```python
[1, 2, 3, 4, 5, 6]
```

Reshape it into:
- 2 rows
- 3 columns

In [2]:
import numpy as np
array = np.array([1,2,3,4,5,6])
reshaped = array.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


# Practice Question

Create a NumPy array with 8 elements.

Reshape it into:
- 4 rows
- 2 columns

In [3]:
array1 = np.array([1,2,3,3,4,5,6,7])
reshaped = array1.reshape(4,2)
print(reshaped)

[[1 2]
 [3 3]
 [4 5]
 [6 7]]


# Practice Question

Create the following 2D array:

```python
[
 [1, 2],
 [3, 4]
]
```

Flatten the array into a 1D array.

In [4]:
matrix = np.array([
    [1,2],
    [3,4]
])
flatten = matrix.flatten()
print(flatten)

[1 2 3 4]


# Practice Question

Create a 2D NumPy array with:
- 3 rows
- 2 columns

Convert it into a 1D array using `flatten()`.

In [5]:
matrix1 = np.array([
    [1,2],
    [4,5],
    [88,90]
])
flatten1 = matrix1.flatten()
print(flatten1)

[ 1  2  4  5 88 90]


# Practice Question

Create two NumPy arrays:

```python
[1, 2, 3]
```

and

```python
[4, 5, 6]
```

Combine both arrays using `concatenate()`.

In [6]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
result = np.concatenate((arr1,arr2))
print(result)

[1 2 3 4 5 6]


# Practice Question

Create a NumPy array:

```python
[10, 20, 30, 40]
```

Split the array into 2 equal parts.

In [7]:
array = np.array([10,20,30,40])
result = np.split(array,2)
print(result)

[array([10, 20]), array([30, 40])]


# Practice Question

Create a NumPy array with 6 elements.

Split the array into:
- 3 equal sections

In [8]:
numbers = np.array([90,76,29,54,92,88])
split = np.split(numbers,3)
print(split)

[array([90, 76]), array([29, 54]), array([92, 88])]


# Practice Question

Create a NumPy array with a missing value using `np.nan`.

Check the missing value positions using `np.isnan()`.

In [9]:
nan_array = np.array([1,2,np.nan,6,3,np.nan])
np.isnan(nan_array)

array([False, False,  True, False, False,  True])

# Practice Question

Create a NumPy array containing:
- integer values
- one missing value using `np.nan`
- print the array


In [10]:
nan_array1 = np.array([1,2,3,np.nan,4,5])
print(nan_array1)

[ 1.  2.  3. nan  4.  5.]


# Chapter 5 — Advanced NumPy Utilities

Welcome to Chapter 5 of NumPy.

In this chapter, we will explore additional NumPy utilities that are useful for numerical computing and future advanced learning.

After learning arrays, operations, statistics, and reshaping, the next step is understanding some important utility functions provided by NumPy.

This chapter focuses on:
- Random number generation
- Random integers
- Seed values
- Important NumPy utilities
- Preparing for advanced libraries like Pandas and Machine Learning

These concepts help build a strong foundation for future data-related libraries and projects.

---

# Topics Covered

1. Random Number Generation  
2. Random Integers  
3. Using Seed Values  
4. Introduction to NumPy Utilities  
5. Preparing for Pandas and Machine Learning

---

# 1. Random Number Generation

## Definition

Random number generation is the process of creating random numerical values using NumPy.

---

## Working

NumPy can generate random decimal numbers automatically.

These values are useful for:
- practice
- simulations
- testing
- machine learning

Random numbers are generated between `0` and `1`.

---

## Syntax

```python
np.random.rand(size)
```

---

## Example

```python
import numpy as np

print(np.random.rand(5))
```

## Output

```python
[0.23 0.91 0.45 0.67 0.12]
```

Output values change every time the code runs.

---

# 2. Random Integers

## Definition

Random integers are randomly generated whole numbers within a specified range.

---

## Working

NumPy can generate integers between:
- starting value
- ending value

Example:

```python
1 to 10
```

NumPy automatically generates random values in that range.

---

## Syntax

```python
np.random.randint(start, end, size)
```

---

## Example

```python
import numpy as np

print(np.random.randint(1, 10, 5))
```

## Output

```python
[2 7 4 1 9]
```

The output changes every time the program runs.

---

# 3. Using Seed Values

## Definition

A seed value fixes the random output so the same random numbers are generated every time.

---

## Working

Normally random numbers change in every execution.

Using:

```python
np.random.seed()
```

makes the random output repeatable.

This is useful when:
- testing programs
- debugging
- sharing results

---

## Syntax

```python
np.random.seed(value)
```

---

## Example

```python
import numpy as np

np.random.seed(1)

print(np.random.randint(1, 10, 5))
```

## Output

```python
[6 9 6 1 1]
```

The output remains the same every time this code runs.

---

# 4. Introduction to NumPy Utilities

## Definition

NumPy utilities are built-in helper functions that simplify array operations and numerical computations.

---

## Working

NumPy provides many utility functions that help:
- create arrays quickly
- generate numerical sequences
- work with mathematical values

Some commonly used utilities are:
- `zeros()`
- `ones()`
- `arange()`
- `linspace()`

These functions help create arrays efficiently without manually entering values.

---

# zeros()

## Definition

Creates an array filled with zeros.

---

## Example

```python
import numpy as np

print(np.zeros(5))
```

## Output

```python
[0. 0. 0. 0. 0.]
```

---

# ones()

## Definition

Creates an array filled with ones.

---

## Example

```python
import numpy as np

print(np.ones(4))
```

## Output

```python
[1. 1. 1. 1.]
```

---

# arange()

## Definition

Creates an array containing values within a specified range.

---

## Working

It works similarly to Python's `range()` function.

---

## Syntax

```python
np.arange(start, stop, step)
```

---

## Example

```python
import numpy as np

print(np.arange(1, 10, 2))
```

## Output

```python
[1 3 5 7 9]
```

---

# linspace()

## Definition

Creates evenly spaced values between two numbers.

---

## Working

Instead of step size, we specify the total number of values needed.

---

## Syntax

```python
np.linspace(start, stop, number_of_values)
```

---

## Example

```python
import numpy as np

print(np.linspace(1, 5, 5))
```

## Output

```python
[1. 2. 3. 4. 5.]
```

---

# 5. Preparing for Pandas and Machine Learning

## Definition

NumPy forms the foundation for advanced Python libraries like Pandas and Machine Learning frameworks.

---

## Working

Libraries such as:
- Pandas
- Scikit-learn
- TensorFlow
- PyTorch

internally use NumPy arrays for computations.

Understanding NumPy helps in:
- data analysis
- machine learning
- scientific computing

Most advanced data operations are built on top of NumPy concepts.

---

## Example

```python
import numpy as np

arr = np.array([10, 20, 30])

print(type(arr))
```

## Output

```python
<class 'numpy.ndarray'>
```

This NumPy array structure is widely used in advanced libraries.

---

# Chapter Summary

In this chapter, we learned:
- How random number generation works
- How to generate random integers
- How seed values work
- Important NumPy utility functions
- How NumPy is connected to Pandas and Machine Learning

This chapter completes the foundational concepts of NumPy required for Data Analytics and Machine Learning.

# Practice Question

Generate 5 random decimal numbers using NumPy.

In [11]:
import numpy as np
array = np.random.rand(5)
print(array)

[0.48069189 0.18196333 0.36782914 0.81420878 0.89891472]


# Practice Question

Generate 5 random integers between:
- 1
- 20

In [12]:
rand_int = np.random.randint(1,20,5)
print(rand_int)

[ 1 12  6  3  5]


# Practice Question

Use `np.random.seed(1)` and generate 5 random integers.

In [13]:
np.random.seed(1)
rand_int = np.random.randint(1,20,5)
print(rand_int)

[ 6 12 13  9 10]


# Practice Question

Create an array of 5 zeros using NumPy.

In [14]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


# Practice Question

Create an array of 5 ones using NumPy.

In [15]:
array_ones = np.ones(5)
print(array_ones)

[1. 1. 1. 1. 1.]


# Practice Question

Create an array using:

```python
np.arange(1, 10, 2)
```

In [16]:
array = np.arange(1,10,2)
print(array)

[1 3 5 7 9]


# Practice Question

Generate 5 evenly spaced values between:
- 1
- 10

using `linspace()`.

In [17]:
linspace_array = np.linspace(1,10,5)
print(linspace_array)

[ 1.    3.25  5.5   7.75 10.  ]


# Practice Question

Create:
- a zeros array
- a ones array
- an array using `arange()`

Print all arrays.

In [18]:
zero = np.zeros(10)
one = np.ones(20)
arange = np.arange(1,30,3)
print(zero)
print(one)
print(arange)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  4  7 10 13 16 19 22 25 28]


# DAY 7

# Introduction to Pandas and Its Role in Real-World Data Analytics

# What is Pandas?

Pandas is a powerful Python library used for:

* data manipulation
* data cleaning
* data analysis
* handling structured datasets

Pandas works mainly with tabular data similar to:

* Excel sheets
* CSV files
* SQL tables

It is one of the most important libraries used in:

* Data Analytics
* Data Science
* Machine Learning
* Deep Learning

---

# Why Pandas is Important

In programming, working with small manually created data is easy.

But in real-world projects, data is usually:

* very large
* messy
* incomplete
* stored in files

Most real-world data comes in formats such as:

* CSV files
* Excel sheets
* databases

Example datasets:

* sales records
* customer details
* employee data
* hospital records
* student databases

Handling this manually becomes difficult.

This is where Pandas becomes important.

---

# Real-World Scenario

Imagine a company has:

* 1 lakh customer records
* 50,000 sales transactions
* multiple Excel sheets
* missing values in datasets

The company wants answers like:

* Which product sells the most?
* Which city generates highest revenue?
* Which customers purchased recently?
* Which employees have highest performance?

Can we analyze this manually using normal Python lists?

It becomes very difficult.

Pandas helps us solve these problems efficiently.

---

# Why Data Analytics Needs Pandas

In data analytics, analysts work with raw datasets.

Raw datasets often contain:

* missing values
* duplicate rows
* inconsistent text
* unnecessary columns
* thousands of records

Before analysis, this data must be:

1. loaded
2. cleaned
3. organized
4. filtered
5. analyzed

Pandas provides tools for all these tasks.

---

# How Pandas Helps Analysts

Pandas helps analysts:

* read CSV and Excel files
* clean messy data
* filter important rows
* sort datasets
* calculate statistics
* group information
* generate insights

This makes analysis:

* faster
* easier
* more efficient

---

# Pandas in Machine Learning and Deep Learning

In Machine Learning and Deep Learning:

* models cannot directly understand raw messy data

Before building models, data must be:

* cleaned
* transformed
* organized

Pandas is commonly used before:

* training ML models
* preprocessing datasets
* feature engineering

This is why Pandas is considered one of the foundational libraries in AI-related fields.

---

# Common Tasks Performed Using Pandas

## Reading Datasets

```python id="y1yyaj"
pd.read_csv()
```

Used to load CSV files.

---

# Understanding Datasets

Functions:

* `head()`
* `info()`
* `shape()`

Used to inspect data.

---

# Cleaning Data

Functions:

* `fillna()`
* `dropna()`
* string cleaning

Used to handle messy datasets.

---

# Filtering Data

Used to select useful records.

Examples:

* students above 80 marks
* customers from Hyderabad
* products with high sales

---

# Grouping and Analysis

Functions:

* `groupby()`
* `mean()`
* `sum()`

Used to summarize and analyze datasets.

---

# Real Workflow Using Pandas

## Step 1 — Collect Data

Data may come from:

* CSV files
* Excel files
* APIs
* databases

---

## Step 2 — Load Data Using Pandas

```python id="cf6smw"
pd.read_csv()
```

---

## Step 3 — Understand the Dataset

Using:

* `head()`
* `info()`
* `shape()`

---

## Step 4 — Clean the Data

Using:

* `fillna()`
* `dropna()`
* removing duplicates
* string cleaning

---

## Step 5 — Analyze the Data

Using:

* filtering
* sorting
* grouping
* aggregation

---

## Step 6 — Generate Insights

Examples:

* highest revenue city
* top-selling product
* average sales
* department-wise salary

---

# Important Note

Pandas is not just about learning functions.

Pandas is mainly used to solve real-world data problems efficiently.


# Module 2 — Introduction to Series and DataFrame

# Introduction

Pandas mainly works with two important data structures:

1. Series
2. DataFrame

These structures help us store, organize, and manipulate data efficiently.

Understanding these two concepts is very important because almost every data analysis operation in Pandas is performed using them.

---

# What is a Series?

A Series is a one-dimensional labeled array in Pandas.

It can store:

* integers
* floats
* strings
* boolean values

A Series is similar to:

* a single column in Excel
* a Python list with labels

---

# Characteristics of Series

A Series:

* stores one-dimensional data
* has indexes
* can hold different data types
* supports fast operations

---

# Importing Pandas

Before creating a Series, we first import Pandas.

```python id="g0cv3v"
import pandas as pd
```

---

# Creating a Simple Series

```python id="lf6e6d"
import pandas as pd

marks = pd.Series([85, 90, 78, 92])

print(marks)
```

---

# Output

```python id="p4q5hn"
0    85
1    90
2    78
3    92
dtype: int64
```

---

# Understanding the Output

In the output:

* left side represents the index
* right side represents the values

Example:

* index 0 → value 85
* index 1 → value 90

---

# Accessing Elements in Series

We can access values using indexes.

```python id="9b2twe"
print(marks[0])
```

---

# Output

```python id="bd6mzm"
85
```

---

# Series with Custom Index

Instead of default indexes, we can create custom labels.

```python id="mwgh3m"
marks = pd.Series(
    [85, 90, 78],
    index=['Math', 'Science', 'English']
)

print(marks)
```

---

# Output

```python id="a7t22v"
Math       85
Science    90
English    78
dtype: int64
```

---

# Accessing Values Using Labels

```python id="e6r0re"
print(marks['Math'])
```

---

# Output

```python id="w4zz8q"
85
```

---

# Why Series is Useful

Series is useful when:

* working with one column of data
* storing labeled information
* performing calculations
* handling time-series data

Examples:

* monthly sales
* student marks
* stock prices

---

# Basic Operations on Series

## Addition

```python id="w7z8zw"
numbers = pd.Series([10, 20, 30])

print(numbers + 5)
```

---

# Output

```python id="ez8r3t"
0    15
1    25
2    35
dtype: int64
```

---

# Multiplication

```python id="wr9e7q"
print(numbers * 2)
```

---

# Output

```python id="8p8fdk"
0    20
1    40
2    60
dtype: int64
```

---

# Important Notes About Series

* Series stores one-dimensional data.
* Series automatically creates indexes if not provided.
* Labels make data easier to understand.
* Series supports vectorized operations.

---

# What is a DataFrame?

A DataFrame is a two-dimensional tabular data structure in Pandas.

A DataFrame contains:

* rows
* columns

It is similar to:

* Excel spreadsheet
* SQL table
* Google Sheets table

---

# Why DataFrame is Important

DataFrame is the most important object in Pandas.

Most data analysis tasks are performed using DataFrames.

Examples:

* sales dataset
* employee records
* customer data
* student database

---

# Structure of a DataFrame

A DataFrame consists of:

* rows → records
* columns → features or attributes

Example:

| Name   | Marks | City      |
| ------ | ----- | --------- |
| Rahul  | 85    | Hyderabad |
| Anjali | 90    | Delhi     |

Here:

* Name, Marks, City → columns
* each student record → row

---

# Creating a DataFrame Using Dictionary

```python id="ph3apw"
import pandas as pd

data = {
    'Name': ['Rahul', 'Anjali', 'Kiran'],
    'Marks': [85, 90, 78],
    'City': ['Hyderabad', 'Delhi', 'Mumbai']
}

df = pd.DataFrame(data)

print(df)
```

---

# Output

```python id="jrtj2u"
      Name  Marks       City
0    Rahul     85  Hyderabad
1   Anjali     90      Delhi
2    Kiran     78     Mumbai
```

---

# Understanding the DataFrame Output

In the DataFrame:

* left side numbers are row indexes
* column names appear at the top
* each row represents one record

---

# Selecting a Single Column

```python id="3qj8dx"
df['Name']
```

---

# Output

```python id="0w4fcq"
0     Rahul
1    Anjali
2     Kiran
Name: Name, dtype: object
```

---

# Selecting Multiple Columns

```python id="13dhnc"
df[['Name', 'Marks']]
```

---

# Output

```python id="b1d3jz"
      Name  Marks
0    Rahul     85
1   Anjali     90
2    Kiran     78
```

---

# Adding a New Column

```python id="7ub0mb"
df['Grade'] = ['A', 'A+', 'B']
```

---

# Viewing Updated DataFrame

```python id="xg0kl0"
print(df)
```

---

# Output

```python id="kpdr5v"
      Name  Marks       City Grade
0    Rahul     85  Hyderabad     A
1   Anjali     90      Delhi    A+
2    Kiran     78     Mumbai     B
```

---

# Important Characteristics of DataFrame

* stores tabular data
* supports multiple data types
* easy data manipulation
* supports filtering and analysis
* works efficiently with large datasets

---

# Difference Between Series and DataFrame

| Series                       | DataFrame               |
| ---------------------------- | ----------------------- |
| One-dimensional              | Two-dimensional         |
| Single column                | Multiple columns        |
| Stores one type of structure | Stores tabular data     |
| Simpler structure            | More powerful structure |

---

# Real-World Importance of DataFrame

DataFrames are heavily used in:

* Data Analytics
* Data Science
* Machine Learning
* Business Reporting

Common uses:

* analyzing sales
* employee management
* customer analysis
* financial reporting

---

# Summary

In this module, we learned:

* what is a Series
* creating Series
* indexing in Series
* Series operations
* what is a DataFrame
* creating DataFrames
* selecting columns
* adding columns
* difference between Series and DataFrame

DataFrame is the foundation of most Pandas operations and is one of the most important concepts in data analytics.


# Practice Question — Create a Fruit Price Series

Create a Pandas Series containing the prices of fruits:

* Apple → 120
* Banana → 40
* Mango → 150
* Orange → 80

Use fruit names as indexes.

Print the Series.


In [19]:
fruits = pd.Series(
    [120,40,150,80],
    index = ["Apple","Banana","Mango","Orange"]
)
print(fruits)

Apple     120
Banana     40
Mango     150
Orange     80
dtype: int64


# Practice Question — Create a Movie Ratings Series

Create a Series containing movie ratings:

```python id="3pnk0o"
[4.5, 3.8, 4.9, 4.2]
```

Use custom indexes:

* Leo
* Pushpa
* KGF
* Jailer

Print the Series.

Then print only the rating of `KGF`.


In [20]:
ratings = pd.Series(
    [4.5,3.8,4.9,4.2],
    index = ["Leo","Pushpa","KGF","Jailer"]
)
print(ratings)

Leo       4.5
Pushpa    3.8
KGF       4.9
Jailer    4.2
dtype: float64


In [21]:
print(ratings["KGF"])

4.9


# Practice Question — Create and Manipulate an Employee DataFrame

Create a DataFrame containing:

| Employee | Salary | Experience |
| -------- | ------ | ---------- |
| Arjun    | 50000  | 2          |
| Meera    | 65000  | 5          |
| David    | 72000  | 6          |
| Sana     | 48000  | 1          |

Perform the following operations:

1. Print the DataFrame
2. Print only the `Salary` column
3. Print `Employee` and `Experience` columns
4. Create a new column called `Bonus`
5. Bonus should be 15% of salary
6. Print the updated DataFrame


In [22]:
data = {
    'Employee':["Arjun","Meera","David","Sana"],
    'Salary':[50000,65000,72000,48000],
    'Experience':[2,5,6,1]
}
df = pd.DataFrame(data)
print(df)

  Employee  Salary  Experience
0    Arjun   50000           2
1    Meera   65000           5
2    David   72000           6
3     Sana   48000           1


In [23]:
df['Salary']

0    50000
1    65000
2    72000
3    48000
Name: Salary, dtype: int64

In [24]:
print(df[['Employee',"Experience"]])

  Employee  Experience
0    Arjun           2
1    Meera           5
2    David           6
3     Sana           1


In [25]:
df["Bonus"] = df['Salary']*(15/100)

In [26]:
df

,Employee,Salary,Experience,Bonus
0,Arjun,50000,2,7500.0
1,Meera,65000,5,9750.0
2,David,72000,6,10800.0
3,Sana,48000,1,7200.0


# Module 3 — Reading CSV Files and Understanding Datasets

# Introduction

In real-world data analytics, data is usually stored in files such as:

* CSV files
* Excel files
* databases

One of the first tasks of a data analyst is:

* loading data
* understanding data structure
* identifying important information

Pandas provides powerful functions to perform these tasks easily.

---

# What is a CSV File?

CSV stands for:

## Comma-Separated Values

A CSV file stores tabular data where:

* each row represents a record
* each column represents a field
* values are separated using commas

Example CSV Data:

```python id="2txy6y"
Name,Marks,City
Rahul,85,Hyderabad
Anjali,90,Delhi
Kiran,78,Mumbai
```

---

# Why CSV Files are Important

CSV files are widely used because:

* simple format
* lightweight
* easy to share
* supported by many tools

Most datasets in data analytics are available in CSV format.

---

# Reading CSV Files Using Pandas

To load CSV data into Pandas, we use:

```python id="g0g4k9"
pd.read_csv()
```

---

# Example

```python id="e7rtxe"
import pandas as pd

df = pd.read_csv('students.csv')

print(df)
```

---

# Understanding read_csv()

`read_csv()`:

* reads CSV files
* converts data into a DataFrame
* automatically detects columns

This is one of the most used Pandas functions in data analytics.

---

# Viewing Dataset Rows

Large datasets may contain thousands of rows.

Instead of printing the entire dataset, we inspect only a few rows.

---

# head()

Displays the first 5 rows by default.

```python id="wtrc2h"
df.head()
```

---

# Example Output

```python id="7mr0ft"
      Name  Marks       City
0    Rahul     85  Hyderabad
1   Anjali     90      Delhi
2    Kiran     78     Mumbai
3    Sneha     88      Pune
4     Arjun     91    Chennai
```

---

# Viewing Specific Number of Rows

```python id="e34qwx"
df.head(3)
```

Displays first 3 rows.

---

# Why head() is Important

Used to:

* quickly inspect data
* verify successful loading
* understand dataset structure

---

# tail()

Displays last 5 rows.

```python id="0k3u1p"
df.tail()
```

---

# Why tail() is Useful

Helpful for:

* checking ending records
* verifying imported data
* understanding dataset completeness

---

# Understanding Dataset Dimensions

## shape

`shape` returns:

* total rows
* total columns

```python id="76pj7o"
df.shape
```

---

# Example Output

```python id="lbn1t0"
(100, 5)
```

Meaning:

* 100 rows
* 5 columns

---

# Why shape is Important

Helps analysts understand:

* dataset size
* dataset complexity

---

# Viewing Column Names

## columns

```python id="hmf7cg"
df.columns
```

---

# Example Output

```python id="vtfy7k"
Index(['Name', 'Marks', 'City'], dtype='object')
```

---

# Why columns is Useful

Used for:

* understanding features
* selecting columns
* identifying naming issues

---

# Understanding Dataset Information

## info()

Displays:

* column names
* data types
* missing values
* memory usage

```python id="m11azn"
df.info()
```

---

# Example Output

```python id="8s5u94"
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
Name      100 non-null object
Marks     100 non-null int64
City      100 non-null object
```

---

# Why info() is Important

Analysts use `info()` to:

* identify data types
* detect missing values
* understand dataset structure

---

# Statistical Summary

## describe()

Provides summary statistics for numerical columns.

```python id="0h0t43"
df.describe()
```

---

# Example Output

```python id="v4q9fh"
           Marks
count   100.000
mean     82.450
std       5.340
min      60.000
max      98.000
```

---

# Understanding describe()

`describe()` provides:

* count
* mean
* standard deviation
* minimum value
* maximum value
* quartiles

---

# Why describe() is Important

Helps analysts:

* understand numerical data
* identify unusual values
* summarize datasets quickly

---

# Selecting Columns

## Single Column Selection

```python id="z6vuy9"
df['Name']
```

---

# Why Single Column Selection is Useful

Used when:

* analyzing one feature
* performing calculations
* cleaning specific columns

---

# Multiple Column Selection

```python id="me0tl9"
df[['Name', 'Marks']]
```

---

# Creating New Columns

We can create new columns using existing data.

Example:

```python id="96v3ka"
df['Bonus'] = df['Marks'] * 0.10
```

---

# Why Creating Columns is Important

Analysts often create:

* calculated fields
* bonus columns
* profit columns
* tax columns
* performance metrics

---

# Saving Data to CSV

After analysis or cleaning, datasets can be saved.

## to_csv()

```python id="x8tx0g"
df.to_csv('output.csv', index=False)
```

---

# Understanding index=False

`index=False` prevents row indexes from being saved into the CSV file.

---

# Real-World Importance of Dataset Inspection

Before analysis, analysts always:

1. load the dataset
2. inspect the structure
3. understand data types
4. identify missing values
5. analyze numerical summaries

This step is extremely important because:

> Good analysis starts with understanding the dataset properly.

---

# Summary

In this module, we learned:

* what is a CSV file
* reading CSV files
* using read_csv()
* viewing rows using head() and tail()
* understanding dataset dimensions using shape
* viewing columns
* using info()
* using describe()
* selecting columns
* creating new columns
* saving datasets using to_csv()

These functions form the foundation of real-world data analysis using Pandas.


# Practice Question — Iris Dataset Basic Inspection

Read the Iris dataset using Pandas.

Perform the following tasks:

1. Print the first 5 rows of the dataset
2. Print the last 5 rows
3. Find the total number of rows and columns
4. Print all column names
5. Use `info()` to understand the dataset structure
6. Use `describe()` to view statistical summary


In [27]:
df1 = pd.read_csv("/kaggle/input/datasets/organizations/uciml/iris/Iris.csv")
df = df1.copy()

In [28]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [29]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [30]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica


In [31]:
df.shape

(150, 6)

In [32]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [34]:
df.describe()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,75.500000,5.843333,3.054000,3.758667,1.198667
std,43.445368,0.828066,0.433594,1.764420,0.763161
min,1.000000,4.300000,2.000000,1.000000,0.100000
25%,38.250000,5.100000,2.800000,1.600000,0.300000
50%,75.500000,5.800000,3.000000,4.350000,1.300000
75%,112.750000,6.400000,3.300000,5.100000,1.800000
max,150.000000,7.900000,4.400000,6.900000,2.500000


# Practice Question — Iris Dataset Column Exploration

Read the Iris dataset using Pandas.

Perform the following tasks:

1. Print only the `sepal_length` column
2. Print only the `petal_length` column
3. Print `sepal_length`, `petal_width`, and `species` columns together
4. Print the first 10 rows of the `species` column
5. Print the `sepal_width` column


In [35]:
df['SepalLengthCm']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLengthCm, Length: 150, dtype: float64

In [36]:
df["PetalLengthCm"]

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: PetalLengthCm, Length: 150, dtype: float64

In [37]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


In [38]:
df[['SepalLengthCm','PetalWidthCm','Species']]

,SepalLengthCm,PetalWidthCm,Species
0,5.1,0.2,Iris-setosa
1,4.9,0.2,Iris-setosa
2,4.7,0.2,Iris-setosa
3,4.6,0.2,Iris-setosa
4,5.0,0.2,Iris-setosa
...,...,...,...
145,6.7,2.3,Iris-virginica
146,6.3,1.9,Iris-virginica
147,6.5,2.0,Iris-virginica
148,6.2,2.3,Iris-virginica


In [39]:
df['Species'].head(10)

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
5    Iris-setosa
6    Iris-setosa
7    Iris-setosa
8    Iris-setosa
9    Iris-setosa
Name: Species, dtype: object

In [40]:
df['SepalWidthCm']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ... 
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: SepalWidthCm, Length: 150, dtype: float64

# Day 8 — Chapter 1

# Row Selection, `loc[]` & `iloc[]`

After loading a dataset, we do not always work with the entire data.

Most of the time, we only need:

* Some rows
* Some columns
* Specific values

Pandas provides different ways to access data easily.

In this chapter, we will learn:

* Row selection
* `loc[]`
* `iloc[]`

---

# Row Selection

A DataFrame is made of rows and columns.

Sometimes we only want:

* First few rows
* Last few rows
* Particular rows from the dataset

---

# Row Slicing

We can select rows using slicing.

## Example

```python id="1snl58"
df[0:5]
```

This selects rows from index `0` to `4`.

Just like Python list slicing:

* Starting index included
* Ending index excluded

---

# `loc[]` — Label Based Selection

`loc[]` is used when we want to access data using row labels and column names.

Think of it like:

> "Go to this row name and this column name."

---

# Syntax

```python id="v7v1a6"
df.loc[row_selection, column_selection]
```

---

# Example

```python id="n59rwr"
df.loc[0]
```

This selects the row with label `0`.

---

# Selecting Multiple Rows

```python id="7bivba"
df.loc[0:5]
```

This selects rows from `0` to `5`.

Important:
In `loc[]`, the ending index is included.

---

# Selecting Rows and Columns Together

```python id="wqwn4t"
df.loc[0:5, ["Name", "Age"]]
```

This means:

* Rows from `0` to `5`
* Only `Name` and `Age` columns

---

# `iloc[]` — Position Based Selection

`iloc[]` is used when we want to access data using position numbers.

Think of it like:

> "Go to row position 0 and column position 1."

---

# Syntax

```python id="7d9e9r"
df.iloc[row_selection, column_selection]
```

---

# Example

```python id="yx63zx"
df.iloc[0]
```

This selects the first row.

---

# Selecting Multiple Rows

```python id="fxozj0"
df.iloc[0:5]
```

This selects rows from position `0` to `4`.

Important:
In `iloc[]`, the ending index is excluded.

---

# Selecting Rows and Columns Together

```python id="cjlwm4"
df.iloc[0:5, 0:3]
```

This means:

* Rows from position `0` to `4`
* Columns from position `0` to `2`

---

# Easy Difference Between `loc[]` and `iloc[]`

| `loc[]`            | `iloc[]`             |
| ------------------ | -------------------- |
| Works with labels  | Works with positions |
| Uses column names  | Uses column numbers  |
| End index included | End index excluded   |

---

# Simple Understanding

Suppose a classroom has:

* Roll numbers
* Bench positions

`loc[]` works like roll numbers.
`iloc[]` works like bench positions.

---

# Why is This Important?

In real projects, datasets can contain thousands of rows.

`loc[]` and `iloc[]` help us quickly access only the required data.


In [41]:
import pandas as pd

students = pd.DataFrame({
    "Name": [
        "Aman", "Riya", "Karan", "Sneha", "Rahul",
        "Priya", "Arjun", "Neha", "Vikram", "Pooja",
        "Rohit", "Anjali", "Varun", "Meera", "Nikhil",
        "Kavya", "Aditya", "Simran", "Yash", "Isha"
    ],
    
    "Age": [
        20, 21, 19, 22, 20,
        21, 23, 20, 22, 19,
        21, 20, 22, 23, 19,
        20, 21, 22, 20, 19
    ],
    
    "Marks": [
        85, 90, 78, 88, 76,
        95, 82, 89, 91, 74,
        80, 87, 92, 79, 84,
        93, 81, 77, 86, 90
    ],
    
    "City": [
        "Delhi", "Mumbai", "Pune", "Chennai", "Hyderabad",
        "Bangalore", "Delhi", "Mumbai", "Pune", "Chennai",
        "Hyderabad", "Bangalore", "Delhi", "Mumbai", "Pune",
        "Chennai", "Hyderabad", "Bangalore", "Delhi", "Mumbai"
    ],
    
    "Course": [
        "Machine Learning",
        "Deep Learning",
        "Natural Language Processing",
        "Computer Vision",
        "Generative AI",
        "Transformers",
        "Python",
        "Data Science",
        "Artificial Intelligence",
        "Machine Learning",
        "Deep Learning",
        "Natural Language Processing",
        "Computer Vision",
        "Generative AI",
        "Transformers",
        "Python",
        "Data Science",
        "Artificial Intelligence",
        "Machine Learning",
        "Deep Learning"
    ]
})

In [42]:
students

,Name,Age,Marks,City,Course
0,Aman,20,85,Delhi,Machine Learning
1,Riya,21,90,Mumbai,Deep Learning
2,Karan,19,78,Pune,Natural Language Processing
3,Sneha,22,88,Chennai,Computer Vision
4,Rahul,20,76,Hyderabad,Generative AI
5,Priya,21,95,Bangalore,Transformers
6,Arjun,23,82,Delhi,Python
7,Neha,20,89,Mumbai,Data Science
8,Vikram,22,91,Pune,Artificial Intelligence
9,Pooja,19,74,Chennai,Machine Learning


In [43]:
students.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    20 non-null     object
 1   Age     20 non-null     int64 
 2   Marks   20 non-null     int64 
 3   City    20 non-null     object
 4   Course  20 non-null     object
dtypes: int64(2), object(3)
memory usage: 932.0+ bytes


In [44]:
students.describe()

,Age,Marks
count,20.000000,20.000000
mean,20.700000,84.850000
std,1.301821,6.200806
min,19.000000,74.000000
25%,20.000000,79.750000
50%,20.500000,85.500000
75%,22.000000,90.000000
max,23.000000,95.000000


# `loc[]` Practice Questions — Student Dataset

## Question 1

Using `loc[]`, select:

* Rows from `0` to `5`
* Columns `"Name"` and `"Course"`

---

## Question 2

Using `loc[]`, select:

* Rows from `3` to `10`
* Columns `"Marks"` and `"City"`

---

## Question 3

Using `loc[]`, select:

* Rows from `5` to `15`
* Columns `"Name"`, `"Age"` and `"Course"`

---

## Question 4

Using `loc[]`, select:

* Rows from `10` to `19`
* Columns `"Course"` and `"Marks"`

---

## Question 5

Using `loc[]`, select:

* Rows from `2` to `8`
* All columns

---

## Question 6

Using `loc[]`, select:

* Rows from `7` to `14`
* Columns `"Name"`, `"City"` and `"Course"`

---

## Question 7

Using `loc[]`, select:

* Rows from `0` to `10`
* Columns `"Age"` and `"Marks"`


In [45]:
# Q1
students.loc[0:5,["Name","Course"]]

,Name,Course
0,Aman,Machine Learning
1,Riya,Deep Learning
2,Karan,Natural Language Processing
3,Sneha,Computer Vision
4,Rahul,Generative AI
5,Priya,Transformers


In [46]:
#Q2
students.loc[3:10,["Marks","City"]]

,Marks,City
3,88,Chennai
4,76,Hyderabad
5,95,Bangalore
6,82,Delhi
7,89,Mumbai
8,91,Pune
9,74,Chennai
10,80,Hyderabad


In [47]:
#Q3
students.loc[5:15,["Name","Age","Course"]]

,Name,Age,Course
5,Priya,21,Transformers
6,Arjun,23,Python
7,Neha,20,Data Science
8,Vikram,22,Artificial Intelligence
9,Pooja,19,Machine Learning
10,Rohit,21,Deep Learning
11,Anjali,20,Natural Language Processing
12,Varun,22,Computer Vision
13,Meera,23,Generative AI
14,Nikhil,19,Transformers


In [48]:
#Q4
students.loc[10:19,['Course','Marks']]

,Course,Marks
10,Deep Learning,80
11,Natural Language Processing,87
12,Computer Vision,92
13,Generative AI,79
14,Transformers,84
15,Python,93
16,Data Science,81
17,Artificial Intelligence,77
18,Machine Learning,86
19,Deep Learning,90


In [49]:
#Q5
students.loc[2:8]

,Name,Age,Marks,City,Course
2,Karan,19,78,Pune,Natural Language Processing
3,Sneha,22,88,Chennai,Computer Vision
4,Rahul,20,76,Hyderabad,Generative AI
5,Priya,21,95,Bangalore,Transformers
6,Arjun,23,82,Delhi,Python
7,Neha,20,89,Mumbai,Data Science
8,Vikram,22,91,Pune,Artificial Intelligence


# `iloc[]` Practice Questions — Student Dataset

## Question 1

Using `iloc[]`, select:

* First 5 rows
* First 2 columns

---

## Question 2

Using `iloc[]`, select:

* Rows from position `5` to `10`
* Columns from position `1` to `3`

---

## Question 3

Using `iloc[]`, select:

* Rows from position `8` to `15`
* Columns from position `0` to `4`

---

## Question 4

Using `iloc[]`, select:

* Rows from position `10` to `19`
* Columns from position `2` to `4`

---

## Question 5

Using `iloc[]`, select:

* Rows from position `3` to `12`
* First 3 columns

---

## Question 6

Using `iloc[]`, select:

* Rows from position `6` to `14`
* Columns from position `0` to `2`

---

## Question 7

Using `iloc[]`, select:

* Rows from position `2` to `9`
* Columns from position `3` to `4`


In [50]:
#Q1
students.iloc[0:5,0:2]

,Name,Age
0,Aman,20
1,Riya,21
2,Karan,19
3,Sneha,22
4,Rahul,20


In [51]:
students.iloc[5:11,1:4]

,Age,Marks,City
5,21,95,Bangalore
6,23,82,Delhi
7,20,89,Mumbai
8,22,91,Pune
9,19,74,Chennai
10,21,80,Hyderabad


In [52]:
students.iloc[8:15,0:4]

,Name,Age,Marks,City
8,Vikram,22,91,Pune
9,Pooja,19,74,Chennai
10,Rohit,21,80,Hyderabad
11,Anjali,20,87,Bangalore
12,Varun,22,92,Delhi
13,Meera,23,79,Mumbai
14,Nikhil,19,84,Pune


In [53]:
students.iloc[3:13,0:3]

,Name,Age,Marks
3,Sneha,22,88
4,Rahul,20,76
5,Priya,21,95
6,Arjun,23,82
7,Neha,20,89
8,Vikram,22,91
9,Pooja,19,74
10,Rohit,21,80
11,Anjali,20,87
12,Varun,22,92


# Day 8 — Chapter 2

# Filtering & Boolean Indexing using Iris Dataset

In real-world datasets, we usually do not need every row.

For example:

* Flowers with petal length greater than 5
* Flowers belonging to a particular species
* Flowers with large sepal width

To get only useful rows, we use filtering.

---

# What is Filtering?

Filtering means selecting rows that satisfy a condition.

Simple meaning:

> Show only the rows that match the requirement.

---

# Boolean Values

Filtering works using:

* `True`
* `False`

If a condition becomes `True`, that row is selected.

If it becomes `False`, that row is ignored.

---

# Filtering with Single Condition

## Example

```python id="yhnc20"
iris[iris["petal_length"] > 5]
```

This means:

> Show flowers where petal length is greater than 5.

---

# Another Example

```python id="ql7z3o"
iris[iris["species"] == "setosa"]
```

This means:

> Show only Setosa flowers.

---

# Multiple Conditions

Sometimes one condition is not enough.

We may need:

* Petal length greater than 5 AND species is virginica
* Sepal width greater than 3 OR petal width greater than 2

For this, Pandas provides:

* `&` → AND
* `|` → OR

---

# AND Condition

Both conditions must be true.

## Example

```python id="rqyo1m"
iris[(iris["petal_length"] > 5) & (iris["species"] == "virginica")]
```

This selects:

* Flowers with petal length greater than 5
* AND species should be virginica

---

# OR Condition

At least one condition must be true.

## Example

```python id="jlwm44"
iris[(iris["sepal_width"] > 3) | (iris["petal_width"] > 2)]
```

This selects flowers where:

* Sepal width is greater than 3
  OR
* Petal width is greater than 2

---

# Important Rule

Always use parentheses around conditions.

Correct:

```python id="7e5tkt"
iris[(iris["petal_length"] > 5) & (iris["species"] == "virginica")]
```

Wrong:

```python id="2rj5yw"
iris[iris["petal_length"] > 5 & iris["species"] == "virginica"]
```

---

# Common Comparison Operators

| Operator | Meaning                  |
| -------- | ------------------------ |
| `>`      | Greater than             |
| `<`      | Less than                |
| `>=`     | Greater than or equal to |
| `<=`     | Less than or equal to    |
| `==`     | Equal to                 |
| `!=`     | Not equal to             |

---

# Simple Understanding

Filtering is like saying:

> "Show only flowers with large petals."

or

> "Show only Setosa flowers."

---

# Why is Filtering Important?

Filtering helps analysts focus only on useful data instead of looking at the complete dataset.


In [54]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `sepal_length` is greater than `5`


In [55]:
df[df["SepalLengthCm"]>5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
15,16,5.7,4.4,1.5,0.4,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `petal_length` is greater than `4`


In [56]:
df[df['PetalLengthCm']>4]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `species` is `"setosa"`


In [57]:
df[df['Species'] == "Iris-setosa"]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `species` is `"virginica"`


In [58]:
df[df['Species'] == "Iris-virginica"]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `sepal_width` is less than `3`


In [59]:
df[df['SepalWidthCm']<3]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
8,9,4.4,2.9,1.4,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `petal_width` is greater than `1.5`


In [60]:
df[df['PetalWidthCm']>1.5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `petal_length` is greater than `6`
* OR `sepal_length` is greater than `7`


In [61]:
df[(df['PetalLengthCm']>6) | (df['SepalLengthCm']>7)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
102,103,7.1,3.0,5.9,2.1,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `sepal_width` is greater than `3`
* AND `petal_width` is greater than `1`


In [62]:
df[(df["SepalWidthCm"]>3) & (df['PetalWidthCm']>1)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
100,101,6.3,3.3,6.0,2.5,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica


# Filtering Question — Iris Dataset

## Question

Show all flowers where:

* `petal_length` is greater than `5`
* AND `species` is `"virginica"`


In [63]:
df[(df["PetalLengthCm"]>5) & (df["Species"] == "Iris-virginica")]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica


# Day 8 — Chapter 3

# Sorting Data using Iris Dataset

Datasets are not always arranged properly.

Sometimes we want:

* Smallest petal length first
* Largest sepal width first
* Flowers arranged species-wise

To arrange data in order, we use sorting.

---

# What is Sorting?

Sorting means arranging data in a particular order.

The two main types are:

* Ascending order
* Descending order

---

# `sort_values()`

Pandas provides the `sort_values()` function to sort data using column values.

---

# Syntax

```python id="jlwmr7"
iris.sort_values(column_name)
```

---

# Ascending Sorting

By default, sorting happens in ascending order.

## Example

```python id="y9d1n8"
iris.sort_values("petal_length")
```

This arranges petal length from smallest to largest.

---

# Descending Sorting

To arrange from largest to smallest, use:

```python id="b3kmtc"
ascending=False
```

## Example

```python id="t0lsn8"
iris.sort_values("sepal_width", ascending=False)
```

This arranges sepal width from largest to smallest.

---

# Sorting Multiple Columns

We can also sort using more than one column.

## Example

```python id="n11zx5"
iris.sort_values(["species", "petal_length"])
```

This first sorts:

1. Species
2. Then petal length within each species

---

# Simple Understanding

Suppose we want:

* Flowers with smallest petals first
* Flowers with biggest petals first

That arrangement is called sorting.

---

# Why is Sorting Important?

Sorting helps us:

* Find highest and lowest values quickly
* Organize reports properly
* Understand patterns easily

---

# Real-World Usage

Sorting is commonly used in:

* Data analysis
* Business reports
* Dashboards
* Ranking systems
* Machine learning preprocessing

It helps organize datasets in a meaningful way.


# Sorting Question — Student Dataset

## Question

Sort the dataset using the `"Marks"` column in ascending order.


In [64]:
students.sort_values("Marks")

,Name,Age,Marks,City,Course
9,Pooja,19,74,Chennai,Machine Learning
4,Rahul,20,76,Hyderabad,Generative AI
17,Simran,22,77,Bangalore,Artificial Intelligence
2,Karan,19,78,Pune,Natural Language Processing
13,Meera,23,79,Mumbai,Generative AI
10,Rohit,21,80,Hyderabad,Deep Learning
16,Aditya,21,81,Hyderabad,Data Science
6,Arjun,23,82,Delhi,Python
14,Nikhil,19,84,Pune,Transformers
0,Aman,20,85,Delhi,Machine Learning


# Sorting Question — Student Dataset

## Question

Sort the dataset using the `"Marks"` column in descending order.


In [65]:
students.sort_values("Marks",ascending = False)

,Name,Age,Marks,City,Course
5,Priya,21,95,Bangalore,Transformers
15,Kavya,20,93,Chennai,Python
12,Varun,22,92,Delhi,Computer Vision
8,Vikram,22,91,Pune,Artificial Intelligence
19,Isha,19,90,Mumbai,Deep Learning
1,Riya,21,90,Mumbai,Deep Learning
7,Neha,20,89,Mumbai,Data Science
3,Sneha,22,88,Chennai,Computer Vision
11,Anjali,20,87,Bangalore,Natural Language Processing
18,Yash,20,86,Delhi,Machine Learning


# Sorting Question — Student Dataset

## Question

Sort the dataset using the `"Age"` column in ascending order.


In [66]:
students.sort_values("Age")

,Name,Age,Marks,City,Course
2,Karan,19,78,Pune,Natural Language Processing
9,Pooja,19,74,Chennai,Machine Learning
14,Nikhil,19,84,Pune,Transformers
19,Isha,19,90,Mumbai,Deep Learning
11,Anjali,20,87,Bangalore,Natural Language Processing
15,Kavya,20,93,Chennai,Python
7,Neha,20,89,Mumbai,Data Science
0,Aman,20,85,Delhi,Machine Learning
18,Yash,20,86,Delhi,Machine Learning
4,Rahul,20,76,Hyderabad,Generative AI


# Sorting Question — Student Dataset

## Question

Sort the dataset using the `"Course"` column in ascending order.


In [67]:
students.sort_values("Course")

,Name,Age,Marks,City,Course
17,Simran,22,77,Bangalore,Artificial Intelligence
8,Vikram,22,91,Pune,Artificial Intelligence
3,Sneha,22,88,Chennai,Computer Vision
12,Varun,22,92,Delhi,Computer Vision
16,Aditya,21,81,Hyderabad,Data Science
7,Neha,20,89,Mumbai,Data Science
19,Isha,19,90,Mumbai,Deep Learning
1,Riya,21,90,Mumbai,Deep Learning
10,Rohit,21,80,Hyderabad,Deep Learning
4,Rahul,20,76,Hyderabad,Generative AI


# Sorting Question — Iris Dataset

## Question

Sort the Iris dataset using the `"sepal_length"` column in ascending order.


In [68]:
df.sort_values("SepalLengthCm")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
13,14,4.3,3.0,1.1,0.1,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
42,43,4.4,3.2,1.3,0.2,Iris-setosa
38,39,4.4,3.0,1.3,0.2,Iris-setosa
41,42,4.5,2.3,1.3,0.3,Iris-setosa
...,...,...,...,...,...,...
122,123,7.7,2.8,6.7,2.0,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica


# Sorting Question — Iris Dataset

## Question

Sort the Iris dataset using the `"species"` column.


In [69]:
df.sort_values("Species")

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
27,28,5.2,3.5,1.5,0.2,Iris-setosa
28,29,5.2,3.4,1.4,0.2,Iris-setosa
29,30,4.7,3.2,1.6,0.2,Iris-setosa
30,31,4.8,3.1,1.6,0.2,Iris-setosa
...,...,...,...,...,...,...
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica


# Sorting Question — Iris Dataset

## Question

Sort the Iris dataset using:

* `"sepal_width"`
* `"petal_length"`
  in descending order.


In [70]:
df.sort_values(["SepalWidthCm","PetalLengthCm"],ascending = False)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
15,16,5.7,4.4,1.5,0.4,Iris-setosa
33,34,5.5,4.2,1.4,0.2,Iris-setosa
32,33,5.2,4.1,1.5,0.1,Iris-setosa
14,15,5.8,4.0,1.2,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
41,42,4.5,2.3,1.3,0.3,Iris-setosa
119,120,6.0,2.2,5.0,1.5,Iris-virginica
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor


In [71]:
import pandas as pd
import numpy as np

data = {
    "Name": [
        "John",
        "Sarah",
        "Mike",
        "Emma",
        "John",
        np.nan,
        "David",
        "Alex"
    ],

    "Age": [
        "25",
        np.nan,
        "30",
        "28",
        "25",
        "35",
        np.nan,
        "27"
    ],

    "City": [
        "Delhi",
        " Mumbai ",
        "CHENNAI",
        "hyderabad",
        "Delhi",
        "MUMBAI",
        np.nan,
        " Hyderabad "
    ],

    "Department": [
        "HR",
        "IT",
        np.nan,
        "Finance",
        "HR",
        "IT",
        "Finance",
        np.nan
    ]
}

df = pd.DataFrame(data)

df

,Name,Age,City,Department
0,John,25,Delhi,HR
1,Sarah,NaN,Mumbai,IT
2,Mike,30,CHENNAI,NaN
3,Emma,28,hyderabad,Finance
4,John,25,Delhi,HR
5,NaN,35,MUMBAI,IT
6,David,NaN,NaN,Finance
7,Alex,27,Hyderabad,NaN


# Why Do We Perform Data Cleaning?

Imagine you are given a dataset from a company.

Your manager asks:

* What is the average employee salary?
* Which city has the most employees?
* Which department performs best?

Can we directly start analyzing the data?

The answer is usually **No**.

Real-world data is rarely perfect. Before analysis, we must understand the data and identify potential issues that may affect our results.

This process is called **Data Cleaning**.

---

# What Type of Data Problems Do We Usually Face?

In real-world projects, analysts mainly encounter two types of problematic data:

## 1. Dirty Data

Dirty data refers to data that contains errors, incorrect values, or poor-quality information.

Examples:

* Missing values
* Duplicate records
* Incorrect data types
* Invalid values
* Inconsistent text

Example:

| Name  | Age | City   |
| ----- | --- | ------ |
| John  | 25  | Delhi  |
| Sarah | NaN | Mumbai |
| John  | 25  | Delhi  |

Problems:

* Missing value in Age
* Duplicate record for John

This is an example of **dirty data** because the data contains quality issues.

---

## 2. Messy Data

Messy data refers to data that is poorly organized, inconsistent, or difficult to work with.

Examples:

* Extra spaces
* Different text formats
* Inconsistent naming conventions
* Columns stored in the wrong format

Example:

| City   |
| ------ |
| Mumbai |
| MUMBAI |
| mumbai |
| Mumbai |

Although all values represent the same city, they are written differently.

This is an example of **messy data** because the information is not standardized.

---

# Dirty Data vs Messy Data

Dirty Data focuses on:

* Missing values
* Duplicate records
* Incorrect values
* Wrong data types

Messy Data focuses on:

* Inconsistent formatting
* Poor organization
* Extra spaces
* Different text representations

Both types of problems can lead to incorrect analysis and misleading results.

Therefore, before performing analysis, we must identify and fix these issues.

---

# Data Cleaning is Not Just Applying Functions

Many beginners think data cleaning means:

```python
dropna()
fillna()
drop_duplicates()
```

and the dataset becomes clean.

This is not true.

The most important part of data cleaning is **making decisions**.

Functions are only tools.

The real skill is deciding when and how to use those tools.

Before applying any cleaning technique, we should understand:

* Why is the data missing?
* Is the missing data important?
* Is a duplicate row actually a mistake?
* Should we remove it or keep it?
* Is a data type incorrect?
* Is the text inconsistency affecting analysis?

Data cleaning requires both technical skills and business understanding.

---

# The Goal of Data Cleaning

The goal is not to remove every problem blindly.

The goal is to make the data:

* Accurate
* Consistent
* Reliable
* Suitable for analysis

Sometimes we remove data.

Sometimes we replace data.

Sometimes we keep the data exactly as it is.

The correct decision depends on the context and the business requirement.

---

# Example 1: Missing Values

Suppose we have:

| Name  | Age |
| ----- | --- |
| John  | 25  |
| Sarah | NaN |
| Mike  | 30  |

Should we remove Sarah?

Not necessarily.

Before making a decision, we should ask:

* How many rows are missing?
* Is Age important for analysis?
* Can the missing value be estimated?
* Will removing the row affect the dataset significantly?

Only after understanding the situation should we decide whether to:

* Remove the row
* Replace the value
* Keep it as missing

---

# Example 2: Duplicate Records

Suppose:

| Employee ID | Name |
| ----------- | ---- |
| 101         | John |
| 101         | John |

These may look like duplicates.

But are they really duplicates?

Maybe:

* One record is old
* One record is updated
* The employee worked on multiple projects
* The duplication occurred because of a system issue

If we blindly remove duplicates, we may lose important information.

---

# Example 3: Inconsistent Text

Suppose we have:

Mumbai

MUMBAI

mumbai

Technically, these are different values.

However, from a business perspective, they represent the same city.

In this situation, cleaning improves consistency without losing information.

---

# The Data Cleaning Mindset

Whenever you find a problem in a dataset, ask:

1. What is the issue?
2. Why did it occur?
3. How does it affect analysis?
4. What are my available options?
5. Which option makes the most sense?

Only after answering these questions should we apply a Pandas function.

---

# Data Cleaning Workflow

A typical data cleaning workflow follows these steps:

### Step 1: Understand the Data

Learn what each column represents and inspect the dataset.

### Step 2: Identify Data Quality Issues

Look for dirty data and messy data.

### Step 3: Decide What Needs to Be Fixed

Determine whether data should be removed, replaced, standardized, or left unchanged.

### Step 4: Apply Cleaning Techniques

Use appropriate Pandas functions to fix the identified issues.

### Step 5: Validate the Results

Verify that the cleaning process improved the quality of the dataset.

---

# Key Takeaway

Data cleaning is not about learning functions.

Data cleaning is about understanding data, identifying problems, and making informed decisions.

Functions such as:

```python
dropna()
fillna()
drop_duplicates()
astype()
str.strip()
```

are simply tools.

The real objective is to transform dirty and messy data into clean, reliable, and analysis-ready data.


# Data Cleaning Functions in Pandas

Now that we understand what dirty data and messy data are, let's learn the Pandas functions used to clean them.

Remember:

Data cleaning is not about memorizing functions.

It is about:

1. Identifying a problem in the data
2. Understanding its impact
3. Choosing the correct cleaning technique
4. Applying the appropriate function

The functions below are tools that help us perform specific cleaning tasks.

---

# 1. Handling Missing Values

## Why Do We Need It?

Missing values are one of the most common data quality issues.

Examples:

- Age is missing
- Salary is missing
- Department is missing

Missing values can:

- Affect calculations
- Produce incorrect statistics
- Cause errors during analysis
- Reduce data quality

Therefore, we need functions to identify and handle missing data.

---

## Functions Used

### isnull()

Checks whether a value is missing.

Returns:

- True → Missing Value
- False → Not Missing

---

### notnull()

Checks whether a value is present.

Returns:

- True → Value Exists
- False → Missing Value

---

### dropna()

Removes rows or columns containing missing values.

Use when:

- Missing records are not useful
- Very few rows contain missing values

---

### fillna()

Replaces missing values with another value.

Use when:

- We do not want to lose data
- Missing values can be reasonably estimated

Example:

- Replace missing age with average age
- Replace missing city with "Unknown"

---

# 2. Handling Duplicate Records

## Why Do We Need It?

Sometimes the same record appears multiple times.

Example:

| Employee_ID | Name |
|-------------|--------|
| 101 | John |
| 101 | John |

Duplicate records can:

- Increase counts incorrectly
- Affect averages
- Produce misleading insights

Therefore, we need functions to identify and remove duplicates.

---

## Functions Used

### duplicated()

Checks whether a row is duplicated.

Returns:

- True → Duplicate Row
- False → Unique Row

---

### drop_duplicates()

Removes duplicate rows from the dataset.

Use when:

- The duplicate is an accidental repetition
- The repeated record provides no additional information

---

# 3. Data Type Conversion

## Why Do We Need It?

Every column has a data type.

Examples:

- Age → Integer
- Salary → Float
- Name → String

Sometimes data is stored in the wrong format.

Example:

```python
"25"
```

This looks like a number but is actually stored as text.

Wrong data types can:

- Prevent calculations
- Cause sorting issues
- Create analysis errors

Therefore, we need data type conversion.

---

## Function Used

### astype()

Converts one data type into another.

Examples:

- String → Integer
- Integer → Float
- Numeric → String

Use when:

- Data is stored in the wrong format
- Analysis requires a different data type

---

# 4. String Cleaning

## Why Do We Need It?

Text data is often inconsistent.

Example:

```text
Mumbai
 MUMBAI
mumbai
```

All represent the same city but are written differently.

Such inconsistencies can:

- Create duplicate categories
- Affect grouping operations
- Produce incorrect reports

Therefore, we need string cleaning functions.

---

# Why Do We Use .str ?

When working with a DataFrame column, Pandas stores text data as a Series.

A Series contains many values.

Example:

```python
df["City"]
```

contains multiple city names.

We cannot directly write:

```python
df["City"].lower()
```

because `.lower()` is a Python string method that works on a single string, not an entire Pandas column.

Instead, Pandas provides the `.str` accessor.

The `.str` accessor allows us to apply string operations to every value in a column.

Example:

```python
df["City"].str.lower()
```

Meaning:

- Access the City column
- Treat it as text data
- Apply `lower()` to every value

Think of `.str` as:

> "I want to perform string operations on this entire column."

---

## Functions Used

### str.lower()

Converts all text to lowercase.

Example:

```text
MUMBAI
```

↓

```text
mumbai
```

---

### str.upper()

Converts all text to uppercase.

Example:

```text
mumbai
```

↓

```text
MUMBAI
```

---

### str.strip()

Removes spaces from the beginning and end of text.

Example:

```text
" Mumbai "
```

↓

```text
"Mumbai"
```

---

### str.replace()

Replaces one text value with another.

Example:

```text
Hyd
```

↓

```text
Hyderabad
```

Use when:

- Values are inconsistent
- Abbreviations need standardization
- Spelling needs correction

---

# Functions Covered Today

```python
# Missing Values
isnull()
notnull()
dropna()
fillna()

# Duplicate Records
duplicated()
drop_duplicates()

# Data Type Conversion
astype()

# String Cleaning
str.lower()
str.upper()
str.strip()
str.replace()
```

---

# Key Takeaway

Data cleaning is not about applying functions blindly.

Each function solves a specific problem:

- Missing Values → isnull(), fillna(), dropna()
- Duplicate Records → duplicated(), drop_duplicates()
- Wrong Data Types → astype()
- Inconsistent Text → str.lower(), str.strip(), str.replace()

The first step is always to understand the problem.

The second step is choosing the right function to solve it.

# Step 1 — Observe the Dataset

Display the dataset and carefully examine it.

```python
df
```

Before applying any cleaning function, try to identify potential issues in the dataset.

Questions:

- Are there any missing values?
- Are there any duplicate records?
- Are all columns stored in the correct data type?
- Do any text values look inconsistent?

In [72]:
df

,Name,Age,City,Department
0,John,25,Delhi,HR
1,Sarah,NaN,Mumbai,IT
2,Mike,30,CHENNAI,NaN
3,Emma,28,hyderabad,Finance
4,John,25,Delhi,HR
5,NaN,35,MUMBAI,IT
6,David,NaN,NaN,Finance
7,Alex,27,Hyderabad,NaN


# Step 2 — Identify Missing Values

Missing values are one of the most common data quality issues.

Use Pandas to locate missing values in the dataset.

```python
df.isnull()
```

Observe which cells contain missing values.

In [73]:
df.isnull()

,Name,Age,City,Department
0,False,False,False,False
1,False,True,False,False
2,False,False,False,True
3,False,False,False,False
4,False,False,False,False
5,True,False,False,False
6,False,True,True,False
7,False,False,False,True


# Step 3 — Count Missing Values

Instead of checking every row manually, count the number of missing values in each column.

```python
df.isnull().sum()
```

Questions:

- Which columns contain missing values?
- Which column has the highest number of missing values?

In [74]:
df.isnull().sum()

Name          1
Age           2
City          1
Department    2
dtype: int64

# Step 4 — Handle Missing Values

We have identified missing values.

Now let's replace them with meaningful values.

Tasks:

- Fill missing values in the `Name` column with `"Unknown"`.
- Fill missing values in the `Department` column with `"Not Assigned"`.
- Fill missing values in the `City` column with `"Unknown City"`.

Use:

```python
fillna()
```

In [75]:
df["Name"] = df["Name"].fillna("Unknown")

In [76]:
df["Department"] = df["Department"].fillna("Not Assigned")

In [77]:
df["City"] = df["City"].fillna("Unknown City")

In [78]:
df

,Name,Age,City,Department
0,John,25,Delhi,HR
1,Sarah,NaN,Mumbai,IT
2,Mike,30,CHENNAI,Not Assigned
3,Emma,28,hyderabad,Finance
4,John,25,Delhi,HR
5,Unknown,35,MUMBAI,IT
6,David,NaN,Unknown City,Finance
7,Alex,27,Hyderabad,Not Assigned


#dStep 5 — Handle Missing Values in Age

The `Age` column contains numeric information.

Instead of replacing missing ages with text, use a numeric value.

Task:

Replace missing ages with the average age of all employees.

Use:

```python
fillna()
```

Questions:

- Why is the average age a better choice than using 0?

In [79]:
df["Age"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 8 entries, 0 to 7
Series name: Age
Non-Null Count  Dtype 
--------------  ----- 
6 non-null      object
dtypes: object(1)
memory usage: 196.0+ bytes


In [80]:
df["Age"] = pd.to_numeric(df["Age"],errors = "coerce")
df["Age"]

0    25.0
1     NaN
2    30.0
3    28.0
4    25.0
5    35.0
6     NaN
7    27.0
Name: Age, dtype: float64

In [81]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df['Age']

0    25.000000
1    28.333333
2    30.000000
3    28.000000
4    25.000000
5    35.000000
6    28.333333
7    27.000000
Name: Age, dtype: float64

# Step 6 — Verify Missing Values

After filling missing values, verify the results.

```python
df.isnull().sum()
```

Question:

- Are there any missing values remaining in the dataset?

In [82]:
df.isnull().sum()

Name          0
Age           0
City          0
Department    0
dtype: int64

# Step 7 — Identify Duplicate Records

Duplicate records can affect analysis and calculations.

Check whether any duplicate rows exist in the dataset.

```python
df.duplicated()
```

Observe the output carefully.

In [83]:
df.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
dtype: bool

# Step 8 — Display Duplicate Records

Display only the duplicate rows.

```python
df[df.duplicated()]
```

Questions:

- Which rows are duplicated?
- Should these records be removed?

In [84]:
df[df.duplicated()]

,Name,Age,City,Department
4,John,25.0,Delhi,HR


# Step 9 — Remove Duplicate Records

Remove duplicate rows from the dataset.

Use:

```python
drop_duplicates()
```

Store the cleaned result back into the DataFrame.

In [85]:
df = df.drop_duplicates()

# Step 10 — Verify Duplicate Removal

Check whether any duplicate records still exist.

```python
df.duplicated().sum()
```

Expected Result:

```python
0
```

In [86]:
df.duplicated().sum()

np.int64(0)

# Step 11 — Inspect Data Types

Before performing analysis, verify the data type of each column.

```python
df.dtypes
```

Questions:

- Is the `Age` column numeric?
- Which columns are text columns?

In [87]:
df.dtypes

Name           object
Age           float64
City           object
Department     object
dtype: object

# Step 12 — Convert Age Data Type

Currently, the `Age` column is stored as text.

Convert it into a numeric data type.

Use:

```python
astype()
```

Verify the result using:

```python
df.dtypes
```

# Step 13 — Investigate Text Data

Examine the values present in the `City` column.

Display all unique city values.

```python
df["City"].unique()
```

Questions:

- Are there extra spaces?
- Are there different letter cases?
- Do some values represent the same city?

In [88]:
df["City"].unique()

array(['Delhi', ' Mumbai ', 'CHENNAI', 'hyderabad', 'MUMBAI',
       'Unknown City', ' Hyderabad '], dtype=object)

# Step 14 — Remove Extra Spaces

Some city names contain unnecessary spaces.

Clean the text using:

```python
str.strip()
```

Display the unique values again and observe the changes.

In [89]:
df["City"] = df["City"].str.strip()

/tmp/ipykernel_16/2983823669.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].str.strip()


# Step 15 — Convert Text to Lowercase

Standardize all city names by converting them to lowercase.

Use:

```python
str.lower()
```

Display the unique values again.

In [90]:
df['City'] = df["City"].str.lower()

/tmp/ipykernel_16/2208294144.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df["City"].str.lower()


In [91]:
df["City"]

0           delhi
1          mumbai
2         chennai
3       hyderabad
5          mumbai
6    unknown city
7       hyderabad
Name: City, dtype: object

# Step 16 — Convert Text to Uppercase

Convert all city names to uppercase.

Use:

```python
str.upper()
```

Observe the output.

This step is only for understanding how the function works.

In [92]:
df["City"] = df["City"].str.upper()

/tmp/ipykernel_16/726177345.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].str.upper()


In [93]:
df["City"]

0           DELHI
1          MUMBAI
2         CHENNAI
3       HYDERABAD
5          MUMBAI
6    UNKNOWN CITY
7       HYDERABAD
Name: City, dtype: object

# Step 17 — Replace Values

Suppose we want to standardize a city name.

Replace:

```text
CHENNAI
```

with

```text
Chennai
```

Use:

```python
str.replace()
```

In [94]:
df["City"] = df["City"].str.replace("CHENNAI","Chennai")

/tmp/ipykernel_16/1382100929.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].str.replace("CHENNAI","Chennai")


In [95]:
df["City"] = df["City"].str.replace("HYDERABAD",'Hyderabad')

/tmp/ipykernel_16/3779693126.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["City"] = df["City"].str.replace("HYDERABAD",'Hyderabad')


In [96]:
df["City"]

0           DELHI
1          MUMBAI
2         Chennai
3       Hyderabad
5          MUMBAI
6    UNKNOWN CITY
7       Hyderabad
Name: City, dtype: object

# Step 18 — Final Verification

Perform a final quality check.

Tasks:

- Check for missing values.
- Check for duplicate records.
- Verify data types.
- Display the cleaned dataset.

Useful Functions:

```python
df.isnull().sum()

df.duplicated().sum()

df.dtypes

df
```

In [97]:
df.isnull().sum()

Name          0
Age           0
City          0
Department    0
dtype: int64

In [98]:
df.duplicated().sum()

np.int64(0)

In [99]:
df.dtypes

Name           object
Age           float64
City           object
Department     object
dtype: object

In [100]:
df

,Name,Age,City,Department
0,John,25.000000,DELHI,HR
1,Sarah,28.333333,MUMBAI,IT
2,Mike,30.000000,Chennai,Not Assigned
3,Emma,28.000000,Hyderabad,Finance
5,Unknown,35.000000,MUMBAI,IT
6,David,28.333333,UNKNOWN CITY,Finance
7,Alex,27.000000,Hyderabad,Not Assigned


# Chapter 1: Introduction to Grouping in Pandas

## What is Grouping?

Grouping is the process of dividing data into different categories based on the values of a column and then performing calculations on each category separately.

In data analysis, we often want answers to questions like:

- What is the average salary in each department?
- How many students are enrolled in each course?
- What is the highest score in each subject?
- How many products belong to each category?

Instead of calculating these values manually, Pandas provides the **groupby()** function.

---

## Real-Life Example

Imagine a classroom with students from different courses.

| Name | Course | Marks |
|--------|---------|---------|
| Rahul | Python | 80 |
| Priya | Python | 90 |
| Ravi | SQL | 70 |
| Neha | SQL | 85 |
| Arjun | Python | 75 |

Suppose we want to find:

- Average marks of Python students
- Average marks of SQL students

Before Pandas, we would first separate students based on their course and then calculate the average marks for each group.

This process is called **Grouping**.

---

## How Grouping Works Internally

When we write:

```python
df.groupby("Course")
```

Pandas internally creates groups like:

Python Group

| Name | Course | Marks |
|--------|---------|---------|
| Rahul | Python | 80 |
| Priya | Python | 90 |
| Arjun | Python | 75 |

SQL Group

| Name | Course | Marks |
|--------|---------|---------|
| Ravi | SQL | 70 |
| Neha | SQL | 85 |

After creating these groups, Pandas can perform calculations on each group separately.

This follows a simple process:

```text
Split → Apply → Combine
```

1. Split the data into groups.
2. Apply a calculation to each group.
3. Combine the results into a new table.

---

## Demonstration: How Grouping Works Internally

```python
import pandas as pd

students = {
    "Name": ["Rahul", "Priya", "Ravi", "Neha", "Arjun"],
    "Course": ["Python", "Python", "SQL", "SQL", "Python"],
    "Marks": [80, 90, 70, 85, 75]
}

df = pd.DataFrame(students)

groups = df.groupby("Course")

for group_name, group_data in groups:
    print(f"\nGroup: {group_name}")
    print(group_data)
```

### Output

```text
Group: Python

    Name  Course  Marks
0  Rahul  Python     80
1  Priya  Python     90
4  Arjun  Python     75


Group: SQL

   Name Course  Marks
2  Ravi    SQL     70
3  Neha    SQL     85
```

Notice that Pandas first separates the data into groups before performing any calculations.

---

## Why is Grouping Important?

Grouping helps us:

- Summarize large datasets
- Compare categories
- Generate business insights
- Create reports quickly
- Perform data analysis efficiently

Most real-world data analysis projects use grouping extensively.

In the next section, we will learn how to perform calculations on these groups using aggregation functions such as:

- mean()
- sum()
- count()
- max()
- min()

# Understanding the Intuition Behind GroupBy

Before learning the syntax of `groupby()`, let's understand what Pandas is actually doing behind the scenes.

Imagine you have the following dataset:

| Name | Course | Marks |
|--------|---------|---------|
| Rahul | Python | 80 |
| Priya | Python | 90 |
| Ravi | SQL | 70 |
| Neha | SQL | 85 |
| Arjun | Python | 75 |

Suppose we ask:

> What is the average marks of students in each course?

---

## Step 1: Split

Pandas first looks at the **Course** column and separates rows having the same course.

### Python Group

| Name | Course | Marks |
|--------|---------|---------|
| Rahul | Python | 80 |
| Priya | Python | 90 |
| Arjun | Python | 75 |

### SQL Group

| Name | Course | Marks |
|--------|---------|---------|
| Ravi | SQL | 70 |
| Neha | SQL | 85 |

At this stage, Pandas has simply broken the original dataset into smaller groups.

```text
Original Data
      ↓
Split by Course
      ↓

Python Group
SQL Group
```

---

## Step 2: Apply

Now Pandas performs the requested operation on each group separately.

If we ask for the average marks:

### Python Group

```text
(80 + 90 + 75) / 3 = 81.67
```

### SQL Group

```text
(70 + 85) / 2 = 77.5
```

```text
Python Group → 81.67
SQL Group    → 77.50
```

---

## Step 3: Combine

Finally, Pandas combines all the results into a new table.

| Course | Average Marks |
|----------|---------------|
| Python | 81.67 |
| SQL | 77.50 |

This is the output we see.

```text
Split
   ↓
Apply
   ↓
Combine
```

---

## Visual Representation

```text
Original Data

Rahul   Python   80
Priya   Python   90
Ravi    SQL      70
Neha    SQL      85
Arjun   Python   75


            ↓ SPLIT


Python Group              SQL Group

Rahul   80                Ravi   70
Priya   90                Neha   85
Arjun   75


            ↓ APPLY


Python Average = 81.67

SQL Average = 77.50


            ↓ COMBINE


Course    Average Marks

Python       81.67
SQL          77.50
```

---

## The GroupBy Formula

Whenever you use:

```python
df.groupby("column")
```

Pandas always follows:

```text
Split → Apply → Combine
```

- Split the data into groups
- Apply a calculation on each group
- Combine the results into a summary table

This is the fundamental idea behind every `groupby()` operation in Pandas.

In [101]:
import pandas as pd

data = {
    "Student_ID": [101,102,103,104,105,106,107,108,109,110,
                   111,112,113,114,115,116,117,118,119,120],

    "Name": [
        "Aarush", "Ishani", "Vihaan", "Navya", "Dhruv",
        "Aadhya", "Yuvan", "Tanirika", "Advik", "Myra",
        "Reyansh", "Anvika", "Shaurya", "Kiara", "Atharv",
        "Samaira", "Pranav", "Vanya", "Rudransh", "Aarini"
    ],

    "Course": [
        "Cyber Security", "Data Science", "Business Analytics", "Cloud Computing",
        "Artificial Intelligence", "Cyber Security", "Data Science", "Cloud Computing",
        "Artificial Intelligence", "Business Analytics", "Data Science", "Cyber Security",
        "Artificial Intelligence", "Cloud Computing", "Business Analytics", "Data Science",
        "Cyber Security", "Cloud Computing", "Artificial Intelligence", "Business Analytics"
    ],

    "Gender": [
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female",
        "Male","Female","Male","Female","Male",
        "Female","Male","Female","Male","Female"
    ],

    "City": [
        "Hyderabad","Bangalore","Chennai","Hyderabad","Pune",
        "Mumbai","Bangalore","Chennai","Pune","Hyderabad",
        "Mumbai","Bangalore","Chennai","Pune","Hyderabad",
        "Mumbai","Bangalore","Chennai","Pune","Hyderabad"
    ],

    "Batch": [
        "Morning","Evening","Morning","Evening","Morning",
        "Morning","Evening","Morning","Evening","Morning",
        "Morning","Evening","Morning","Evening","Morning",
        "Morning","Evening","Morning","Evening","Morning"
    ],

    "Year": [
        1,2,1,3,2,
        1,2,3,2,1,
        2,1,3,2,1,
        2,3,1,2,3
    ],

    "Scholarship": [
        "Yes","No","Yes","No","Yes",
        "No","Yes","No","Yes","No",
        "Yes","No","Yes","No","Yes",
        "No","Yes","No","Yes","No"
    ],

    "Marks": [
        88,92,76,85,95,
        81,79,90,87,84,
        91,89,93,78,82,
        96,80,86,94,88
    ],

    "Attendance": [
        92,96,85,90,98,
        88,84,94,91,89,
        95,93,97,87,86,
        99,82,92,96,90
    ],

    "Projects_Completed": [
        3,4,2,5,4,
        3,2,4,5,3,
        4,3,5,2,3,
        4,2,5,4,3
    ],

    "Placement_Preparation_Hours": [
        5,8,3,7,10,
        4,5,8,9,6,
        7,5,10,4,6,
        8,3,9,7,5
    ]
}

df1 = pd.DataFrame(data)

df1

,Student_ID,Name,Course,Gender,City,Batch,Year,Scholarship,Marks,Attendance,Projects_Completed,Placement_Preparation_Hours
0,101,Aarush,Cyber Security,Male,Hyderabad,Morning,1,Yes,88,92,3,5
1,102,Ishani,Data Science,Female,Bangalore,Evening,2,No,92,96,4,8
2,103,Vihaan,Business Analytics,Male,Chennai,Morning,1,Yes,76,85,2,3
3,104,Navya,Cloud Computing,Female,Hyderabad,Evening,3,No,85,90,5,7
4,105,Dhruv,Artificial Intelligence,Male,Pune,Morning,2,Yes,95,98,4,10
5,106,Aadhya,Cyber Security,Female,Mumbai,Morning,1,No,81,88,3,4
6,107,Yuvan,Data Science,Male,Bangalore,Evening,2,Yes,79,84,2,5
7,108,Tanirika,Cloud Computing,Female,Chennai,Morning,3,No,90,94,4,8
8,109,Advik,Artificial Intelligence,Male,Pune,Evening,2,Yes,87,91,5,9
9,110,Myra,Business Analytics,Female,Hyderabad,Morning,1,No,84,89,3,6


# Practice Question

Find the average attendance of male and female students.

In [102]:
df1.groupby("Gender")["Attendance"].mean()

Gender
Female    91.8
Male      90.6
Name: Attendance, dtype: float64

# Practice Question

Find the total number of students enrolled in each course.

In [103]:
df1.groupby("Course")["Student_ID"].count()

Course
Artificial Intelligence    4
Business Analytics         4
Cloud Computing            4
Cyber Security             4
Data Science               4
Name: Student_ID, dtype: int64

# Practice Question

Find the highest marks scored by students in each course.

In [104]:
df1.groupby("Course")["Marks"].max()

Course
Artificial Intelligence    95
Business Analytics         88
Cloud Computing            90
Cyber Security             89
Data Science               96
Name: Marks, dtype: int64

# Practice Question

Find the average attendance of students from each city.

In [105]:
df1.groupby("City")["Attendance"].mean()

City
Bangalore    88.75
Chennai      92.00
Hyderabad    89.40
Mumbai       94.00
Pune         93.00
Name: Attendance, dtype: float64

# Practice Question

Find the total projects completed by students in each batch.

In [106]:
df1.groupby("Batch")["Projects_Completed"].sum()

Batch
Evening    27
Morning    43
Name: Projects_Completed, dtype: int64

# Practice Question

Find the average marks of scholarship and non-scholarship students.

In [107]:
df1.groupby("Scholarship")["Marks"].mean()

Scholarship
No     86.9
Yes    86.5
Name: Marks, dtype: float64

# Practice Question

Find the average placement preparation hours for each course.

In [108]:
df1.groupby("Course")["Placement_Preparation_Hours"].mean()

Course
Artificial Intelligence    9.00
Business Analytics         5.00
Cloud Computing            7.00
Cyber Security             4.25
Data Science               7.00
Name: Placement_Preparation_Hours, dtype: float64

# Practice Question

Find the average marks for each course and gender combination.

In [109]:
df1.groupby(["Course","Gender"])["Marks"].mean()

Course                   Gender
Artificial Intelligence  Male      92.25
Business Analytics       Female    86.00
                         Male      79.00
Cloud Computing          Female    84.75
Cyber Security           Female    85.00
                         Male      84.00
Data Science             Female    94.00
                         Male      85.00
Name: Marks, dtype: float64

# Practice Question

Find the total number of students in each city and course combination.

In [110]:
df1.groupby(["City","Course"])["Student_ID"].count()

City       Course                 
Bangalore  Cyber Security             2
           Data Science               2
Chennai    Artificial Intelligence    1
           Business Analytics         1
           Cloud Computing            2
Hyderabad  Business Analytics         3
           Cloud Computing            1
           Cyber Security             1
Mumbai     Cyber Security             1
           Data Science               2
Pune       Artificial Intelligence    3
           Cloud Computing            1
Name: Student_ID, dtype: int64

# Challenge Question

Find the average attendance for each academic year and course combination.

In [111]:
df1.groupby(["Year","Course"])["Attendance"].mean()

Year  Course                 
1     Business Analytics         86.666667
      Cloud Computing            92.000000
      Cyber Security             91.000000
2     Artificial Intelligence    95.000000
      Cloud Computing            87.000000
      Data Science               93.500000
3     Artificial Intelligence    97.000000
      Business Analytics         90.000000
      Cloud Computing            92.000000
      Cyber Security             82.000000
Name: Attendance, dtype: float64

# Chapter 2: Aggregation with agg()

## Why Do We Need agg()?

So far, we have learned how to group data and perform a single calculation on each group.

For example:

```python
df1.groupby("Course")["Marks"].mean()
```

This gives the average marks for each course.

Similarly:

```python
df1.groupby("Course")["Marks"].max()
```

returns the highest marks for each course.

And:

```python
df1.groupby("Course")["Marks"].count()
```

returns the number of students in each course.

---

The problem is that if we need multiple statistics, we have to write multiple commands.

```python
df1.groupby("Course")["Marks"].mean()

df1.groupby("Course")["Marks"].max()

df1.groupby("Course")["Marks"].min()

df1.groupby("Course")["Marks"].count()
```

This is repetitive and inefficient.

---

## Introducing agg()

The `agg()` function allows us to perform multiple aggregation operations in a single command.

### Syntax

```python
df.groupby("column")["numeric_column"].agg(
    ["aggregation1", "aggregation2", ...]
)
```

---

## Example

```python
df1.groupby("Course")["Marks"].agg(
    ["mean", "max", "min", "count"]
)
```

### Output

| Course | mean | max | min | count |
|----------|----------|----------|----------|----------|
| Artificial Intelligence | ... | ... | ... | ... |
| Business Analytics | ... | ... | ... | ... |
| Cloud Computing | ... | ... | ... | ... |
| Cyber Security | ... | ... | ... | ... |
| Data Science | ... | ... | ... | ... |

---

## What Does agg() Do Internally?

Just like GroupBy follows:

```text
Split → Apply → Combine
```

`agg()` applies multiple calculations during the Apply step.

```text
Course Group
      ↓

mean()
max()
min()
count()

      ↓

Combined Report
```

---

## Benefits of agg()

- Reduces repetitive code
- Generates summary reports quickly
- Performs multiple calculations at once
- Commonly used in real-world data analysis

---

## Next

In the next section, we will learn how to use `agg()` on multiple columns to create more detailed reports.

# Practice Question

For each course, find:

- Average Marks
- Highest Marks
- Lowest Marks
- Number of Students

In [112]:
df1.groupby("Course")["Marks"].agg(["mean","max","min","count"])

,mean,max,min,count
Course,,,,
Artificial Intelligence,92.25,95,87,4
Business Analytics,82.50,88,76,4
Cloud Computing,84.75,90,78,4
Cyber Security,84.50,89,80,4
Data Science,89.50,96,79,4


# Practice Question

For each city, find:

- Average Attendance
- Highest Attendance
- Lowest Attendance

In [113]:
df1.groupby("City")["Attendance"].agg(["mean","min","max"])

,mean,min,max
City,,,
Bangalore,88.75,82,96
Chennai,92.00,85,97
Hyderabad,89.40,86,92
Mumbai,94.00,88,99
Pune,93.00,87,98


# Practice Question

For each batch, find:

- Average Marks
- Highest Marks
- Total Marks

In [114]:
df1.groupby("Batch")["Marks"].agg(["mean","max","sum"])

,mean,max,sum
Batch,,,
Evening,85.5,94,684
Morning,87.5,96,1050


# Practice Question

For each course, find:

- Average Attendance
- Highest Attendance
- Lowest Attendance
- Total Attendance

In [115]:
df1.groupby("Course")["Attendance"].agg(["mean","min","max","sum"])

,mean,min,max,sum
Course,,,,
Artificial Intelligence,95.50,91,98,382
Business Analytics,87.50,85,90,350
Cloud Computing,90.75,87,94,363
Cyber Security,88.75,82,93,355
Data Science,93.50,84,99,374


# Challenge Question

For each course, create a report showing:

- Average Marks
- Average Attendance
- Total Projects Completed
- Average Placement Preparation Hours

In [116]:
df1.groupby("Course").agg({
    "Marks":"mean",
    "Attendance":"mean",
    "Projects_Completed":"sum",
    "Placement_Preparation_Hours":"mean"
})

,Marks,Attendance,Projects_Completed,Placement_Preparation_Hours
Course,,,,
Artificial Intelligence,92.25,95.50,18,9.00
Business Analytics,82.50,87.50,11,5.00
Cloud Computing,84.75,90.75,16,7.00
Cyber Security,84.50,88.75,11,4.25
Data Science,89.50,93.50,14,7.00
